# Generated by Django 5.0.7 on 2024-12-03 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('efinalapp', '0002_myregisters'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Myregisters',
            new_name='Myregister',
        ),
    ]
